<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class FoodnutriTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $base = [
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ];

        \DB::table('foodnutri')->insert([
            ['food_id' => 1, 'nutri_id' => 1] + $base,    ['food_id' => 1, 'nutri_id' => 2] + $base,    ['food_id' => 1, 'nutri_id' => 3] + $base,    ['food_id' => 1, 'nutri_id' => 4] + $base,                                ['food_id' => 1, 'nutri_id' => 12] + $base,        ['food_id' => 1, 'nutri_id' => 14] + $base,        ['food_id' => 1, 'nutri_id' => 16] + $base,                                            ['food_id' => 1, 'nutri_id' => 27] + $base,                    ['food_id' => 1, 'nutri_id' => 32] + $base,
            ['food_id' => 2, 'nutri_id' => 1] + $base,            ['food_id' => 2, 'nutri_id' => 4] + $base,                ['food_id' => 2, 'nutri_id' => 8] + $base,                                        ['food_id' => 2, 'nutri_id' => 18] + $base,    ['food_id' => 2, 'nutri_id' => 19] + $base,                        ['food_id' => 2, 'nutri_id' => 25] + $base,                        ['food_id' => 2, 'nutri_id' => 31] + $base,
            ['food_id' => 3, 'nutri_id' => 1] + $base,                            ['food_id' => 3, 'nutri_id' => 8] + $base,                    ['food_id' => 3, 'nutri_id' => 13] + $base,                                        ['food_id' => 3, 'nutri_id' => 23] + $base,        ['food_id' => 3, 'nutri_id' => 25] + $base,
            ['food_id' => 4, 'nutri_id' => 1] + $base,            ['food_id' => 4, 'nutri_id' => 4] + $base,    ['food_id' => 4, 'nutri_id' => 5] + $base,        ['food_id' => 4, 'nutri_id' => 7] + $base,            ['food_id' => 4, 'nutri_id' => 10] + $base,    ['food_id' => 4, 'nutri_id' => 11] + $base,    ['food_id' => 4, 'nutri_id' => 12] + $base,                    ['food_id' => 4, 'nutri_id' => 17] + $base,        ['food_id' => 4, 'nutri_id' => 19] + $base,        ['food_id' => 4, 'nutri_id' => 21] + $base,    ['food_id' => 4, 'nutri_id' => 22] + $base,    ['food_id' => 4, 'nutri_id' => 23] + $base,    ['food_id' => 4, 'nutri_id' => 24] + $base,    ['food_id' => 4, 'nutri_id' => 25] + $base,    ['food_id' => 4, 'nutri_id' => 26] + $base,    ['food_id' => 4, 'nutri_id' => 27] + $base,    ['food_id' => 4, 'nutri_id' => 28] + $base,    ['food_id' => 4, 'nutri_id' => 29] + $base,                ['food_id' => 4, 'nutri_id' => 33] + $base,
            ['food_id' => 5, 'nutri_id' => 1] + $base,            ['food_id' => 5, 'nutri_id' => 4] + $base,    ['food_id' => 5, 'nutri_id' => 5] + $base,            ['food_id' => 5, 'nutri_id' => 8] + $base,    ['food_id' => 5, 'nutri_id' => 9] + $base,                    ['food_id' => 5, 'nutri_id' => 14] + $base,
            ['food_id' => 6, 'nutri_id' => 1] + $base,                                ['food_id' => 6, 'nutri_id' => 9] + $base,                        ['food_id' => 6, 'nutri_id' => 15] + $base,                                                                ['food_id' => 6, 'nutri_id' => 31] + $base,
            ['food_id' => 7, 'nutri_id' => 1] + $base,            ['food_id' => 7, 'nutri_id' => 4] + $base,    ['food_id' => 7, 'nutri_id' => 5] + $base,            ['food_id' => 7, 'nutri_id' => 8] + $base,    ['food_id' => 7, 'nutri_id' => 9] + $base,                    ['food_id' => 7, 'nutri_id' => 14] + $base,    ['food_id' => 7, 'nutri_id' => 15] + $base,    ['food_id' => 7, 'nutri_id' => 16] + $base,    ['food_id' => 7, 'nutri_id' => 17] + $base,                            ['food_id' => 7, 'nutri_id' => 24] + $base,    ['food_id' => 7, 'nutri_id' => 25] + $base,        ['food_id' => 7, 'nutri_id' => 27] + $base,
            ['food_id' => 8, 'nutri_id' => 1] + $base,            ['food_id' => 8, 'nutri_id' => 4] + $base,    ['food_id' => 8, 'nutri_id' => 5] + $base,                                ['food_id' => 8, 'nutri_id' => 13] + $base,        ['food_id' => 8, 'nutri_id' => 15] + $base,    ['food_id' => 8, 'nutri_id' => 16] + $base,                                                        ['food_id' => 8, 'nutri_id' => 30] + $base,    ['food_id' => 8, 'nutri_id' => 31] + $base,
            ['food_id' => 9, 'nutri_id' => 1] + $base,                ['food_id' => 9, 'nutri_id' => 5] + $base,            ['food_id' => 9, 'nutri_id' => 8] + $base,                            ['food_id' => 9, 'nutri_id' => 15] + $base,
            ['food_id' => 10, 'nutri_id' => 1] + $base,                                    ['food_id' => 10, 'nutri_id' => 10] + $base,        ['food_id' => 10, 'nutri_id' => 12] + $base,    ['food_id' => 10, 'nutri_id' => 13] + $base,                ['food_id' => 10, 'nutri_id' => 17] + $base,                ['food_id' => 10, 'nutri_id' => 21] + $base,            ['food_id' => 10, 'nutri_id' => 24] + $base,    ['food_id' => 10, 'nutri_id' => 25] + $base,    ['food_id' => 10, 'nutri_id' => 26] + $base,    ['food_id' => 10, 'nutri_id' => 27] + $base,        ['food_id' => 10, 'nutri_id' => 29] + $base,        ['food_id' => 10, 'nutri_id' => 31] + $base,
            ['food_id' => 11, 'nutri_id' => 1] + $base,                                                        ['food_id' => 11, 'nutri_id' => 15] + $base,                                        ['food_id' => 11, 'nutri_id' => 25] + $base,        ['food_id' => 11, 'nutri_id' => 27] + $base,
            ['food_id' => 12, 'nutri_id' => 1] + $base,
            ['food_id' => 13, 'nutri_id' => 1] + $base,
            ['food_id' => 14, 'nutri_id' => 1] + $base,                                                                ['food_id' => 14, 'nutri_id' => 17] + $base,                ['food_id' => 14, 'nutri_id' => 21] + $base,        ['food_id' => 14, 'nutri_id' => 23] + $base,        ['food_id' => 14, 'nutri_id' => 25] + $base,    ['food_id' => 14, 'nutri_id' => 26] + $base,        ['food_id' => 14, 'nutri_id' => 28] + $base,    ['food_id' => 14, 'nutri_id' => 29] + $base,
            ['food_id' => 15, 'nutri_id' => 1] + $base,            ['food_id' => 15, 'nutri_id' => 4] + $base,    ['food_id' => 15, 'nutri_id' => 5] + $base,                                                                                        ['food_id' => 15, 'nutri_id' => 27] + $base,
            ['food_id' => 16, 'nutri_id' => 1] + $base,
            ['food_id' => 17, 'nutri_id' => 1] + $base,                                                            ['food_id' => 17, 'nutri_id' => 16] + $base,
            ['food_id' => 18, 'nutri_id' => 2] + $base,
            ['food_id' => 19, 'nutri_id' => 2] + $base,    ['food_id' => 19, 'nutri_id' => 3] + $base,    ['food_id' => 19, 'nutri_id' => 4] + $base,                        ['food_id' => 19, 'nutri_id' => 10] + $base,
            ['food_id' => 20, 'nutri_id' => 2] + $base,    ['food_id' => 20, 'nutri_id' => 3] + $base,        ['food_id' => 20, 'nutri_id' => 5] + $base,            ['food_id' => 20, 'nutri_id' => 8] + $base,
            ['food_id' => 21, 'nutri_id' => 2] + $base,
            ['food_id' => 22, 'nutri_id' => 2] + $base,    ['food_id' => 22, 'nutri_id' => 3] + $base,
            ['food_id' => 23, 'nutri_id' => 2] + $base,
            ['food_id' => 24, 'nutri_id' => 2] + $base,    ['food_id' => 24, 'nutri_id' => 3] + $base,
            ['food_id' => 25, 'nutri_id' => 2] + $base,        ['food_id' => 25, 'nutri_id' => 4] + $base,                        ['food_id' => 25, 'nutri_id' => 10] + $base,        ['food_id' => 25, 'nutri_id' => 12] + $base,        ['food_id' => 25, 'nutri_id' => 14] + $base,                                    ['food_id' => 25, 'nutri_id' => 23] + $base,        ['food_id' => 25, 'nutri_id' => 25] + $base,    ['food_id' => 25, 'nutri_id' => 26] + $base,    ['food_id' => 25, 'nutri_id' => 27] + $base,    ['food_id' => 25, 'nutri_id' => 28] + $base,    ['food_id' => 25, 'nutri_id' => 29] + $base,                ['food_id' => 25, 'nutri_id' => 33] + $base,
            ['food_id' => 26, 'nutri_id' => 2] + $base,        ['food_id' => 26, 'nutri_id' => 4] + $base,                        ['food_id' => 26, 'nutri_id' => 10] + $base,            ['food_id' => 26, 'nutri_id' => 13] + $base,                        ['food_id' => 26, 'nutri_id' => 19] + $base,                    ['food_id' => 26, 'nutri_id' => 24] + $base,                ['food_id' => 26, 'nutri_id' => 28] + $base,
            ['food_id' => 27, 'nutri_id' => 2] + $base,        ['food_id' => 27, 'nutri_id' => 4] + $base,                        ['food_id' => 27, 'nutri_id' => 10] + $base,                                                                        ['food_id' => 27, 'nutri_id' => 28] + $base,
            ['food_id' => 28, 'nutri_id' => 2] + $base,        ['food_id' => 28, 'nutri_id' => 4] + $base,                        ['food_id' => 28, 'nutri_id' => 10] + $base,        ['food_id' => 28, 'nutri_id' => 12] + $base,                ['food_id' => 28, 'nutri_id' => 16] + $base,        ['food_id' => 28, 'nutri_id' => 18] + $base,                                            ['food_id' => 28, 'nutri_id' => 29] + $base,                ['food_id' => 28, 'nutri_id' => 33] + $base,
            ['food_id' => 29, 'nutri_id' => 2] + $base,        ['food_id' => 29, 'nutri_id' => 4] + $base,                                        ['food_id' => 29, 'nutri_id' => 14] + $base,        ['food_id' => 29, 'nutri_id' => 16] + $base,        ['food_id' => 29, 'nutri_id' => 18] + $base,    ['food_id' => 29, 'nutri_id' => 19] + $base,
            ['food_id' => 30, 'nutri_id' => 3] + $base,
            ['food_id' => 31, 'nutri_id' => 3] + $base,
            ['food_id' => 32, 'nutri_id' => 3] + $base,
            ['food_id' => 33, 'nutri_id' => 3] + $base,                    ['food_id' => 33, 'nutri_id' => 8] + $base,                                                            ['food_id' => 33, 'nutri_id' => 23] + $base,        ['food_id' => 33, 'nutri_id' => 25] + $base,
            ['food_id' => 34, 'nutri_id' => 3] + $base,                    ['food_id' => 34, 'nutri_id' => 8] + $base,
            ['food_id' => 35, 'nutri_id' => 4] + $base,                        ['food_id' => 35, 'nutri_id' => 10] + $base,
            ['food_id' => 36, 'nutri_id' => 4] + $base,
            ['food_id' => 37, 'nutri_id' => 4] + $base,                        ['food_id' => 37, 'nutri_id' => 10] + $base,
            ['food_id' => 38, 'nutri_id' => 4] + $base,
            ['food_id' => 39, 'nutri_id' => 4] + $base,            ['food_id' => 39, 'nutri_id' => 7] + $base,                                        ['food_id' => 39, 'nutri_id' => 17] + $base,                ['food_id' => 39, 'nutri_id' => 21] + $base,    ['food_id' => 39, 'nutri_id' => 22] + $base,    ['food_id' => 39, 'nutri_id' => 23] + $base,    ['food_id' => 39, 'nutri_id' => 24] + $base,        ['food_id' => 39, 'nutri_id' => 26] + $base,                ['food_id' => 39, 'nutri_id' => 30] + $base,
            ['food_id' => 40, 'nutri_id' => 4] + $base,    ['food_id' => 40, 'nutri_id' => 5] + $base,        ['food_id' => 40, 'nutri_id' => 7] + $base,    ['food_id' => 40, 'nutri_id' => 8] + $base,                    ['food_id' => 40, 'nutri_id' => 13] + $base,                ['food_id' => 40, 'nutri_id' => 17] + $base,                ['food_id' => 40, 'nutri_id' => 21] + $base,    ['food_id' => 40, 'nutri_id' => 22] + $base,    ['food_id' => 40, 'nutri_id' => 23] + $base,    ['food_id' => 40, 'nutri_id' => 24] + $base,                        ['food_id' => 40, 'nutri_id' => 30] + $base,        ['food_id' => 40, 'nutri_id' => 32] + $base,
            ['food_id' => 41, 'nutri_id' => 4] + $base,    ['food_id' => 41, 'nutri_id' => 5] + $base,            ['food_id' => 41, 'nutri_id' => 8] + $base,                ['food_id' => 41, 'nutri_id' => 12] + $base,    ['food_id' => 41, 'nutri_id' => 13] + $base,                    ['food_id' => 41, 'nutri_id' => 18] + $base,
            ['food_id' => 42, 'nutri_id' => 4] + $base,
            ['food_id' => 43, 'nutri_id' => 4] + $base,    ['food_id' => 43, 'nutri_id' => 5] + $base,                                        ['food_id' => 43, 'nutri_id' => 15] + $base,
            ['food_id' => 44, 'nutri_id' => 4] + $base,
            ['food_id' => 45, 'nutri_id' => 4] + $base,
            ['food_id' => 46, 'nutri_id' => 1] + $base,    ['food_id' => 46, 'nutri_id' => 2] + $base,    ['food_id' => 46, 'nutri_id' => 3] + $base,    ['food_id' => 46, 'nutri_id' => 4] + $base,
            ['food_id' => 47, 'nutri_id' => 4] + $base,    ['food_id' => 47, 'nutri_id' => 5] + $base,                            ['food_id' => 47, 'nutri_id' => 12] + $base,                            ['food_id' => 47, 'nutri_id' => 19] + $base,        ['food_id' => 47, 'nutri_id' => 21] + $base,            ['food_id' => 47, 'nutri_id' => 24] + $base,    ['food_id' => 47, 'nutri_id' => 25] + $base,    ['food_id' => 47, 'nutri_id' => 26] + $base,    ['food_id' => 47, 'nutri_id' => 27] + $base,                ['food_id' => 47, 'nutri_id' => 31] + $base,        ['food_id' => 47, 'nutri_id' => 33] + $base,
            ['food_id' => 48, 'nutri_id' => 4] + $base,    ['food_id' => 48, 'nutri_id' => 5] + $base,            ['food_id' => 48, 'nutri_id' => 8] + $base,                        ['food_id' => 48, 'nutri_id' => 14] + $base,        ['food_id' => 48, 'nutri_id' => 16] + $base,                                                            ['food_id' => 48, 'nutri_id' => 31] + $base,
            ['food_id' => 49, 'nutri_id' => 4] + $base,    ['food_id' => 49, 'nutri_id' => 5] + $base,        ['food_id' => 49, 'nutri_id' => 7] + $base,    ['food_id' => 49, 'nutri_id' => 8] + $base,            ['food_id' => 49, 'nutri_id' => 11] + $base,        ['food_id' => 49, 'nutri_id' => 13] + $base,    ['food_id' => 49, 'nutri_id' => 14] + $base,    ['food_id' => 49, 'nutri_id' => 15] + $base,    ['food_id' => 49, 'nutri_id' => 16] + $base,    ['food_id' => 49, 'nutri_id' => 17] + $base,        ['food_id' => 49, 'nutri_id' => 19] + $base,    ['food_id' => 49, 'nutri_id' => 20] + $base,                    ['food_id' => 49, 'nutri_id' => 25] + $base,    ['food_id' => 49, 'nutri_id' => 26] + $base,            ['food_id' => 49, 'nutri_id' => 29] + $base,
            ['food_id' => 50, 'nutri_id' => 4] + $base,    ['food_id' => 50, 'nutri_id' => 5] + $base,                                                                                    ['food_id' => 50, 'nutri_id' => 26] + $base,        ['food_id' => 50, 'nutri_id' => 28] + $base,    ['food_id' => 50, 'nutri_id' => 29] + $base,            ['food_id' => 50, 'nutri_id' => 32] + $base,
            ['food_id' => 51, 'nutri_id' => 4] + $base,            ['food_id' => 51, 'nutri_id' => 7] + $base,                ['food_id' => 51, 'nutri_id' => 11] + $base,                                            ['food_id' => 51, 'nutri_id' => 22] + $base,                ['food_id' => 51, 'nutri_id' => 26] + $base,                ['food_id' => 51, 'nutri_id' => 30] + $base,        ['food_id' => 51, 'nutri_id' => 32] + $base,
            ['food_id' => 52, 'nutri_id' => 4] + $base,    ['food_id' => 52, 'nutri_id' => 5] + $base,
            ['food_id' => 53, 'nutri_id' => 4] + $base,    ['food_id' => 53, 'nutri_id' => 5] + $base,                                                                                                        ['food_id' => 53, 'nutri_id' => 31] + $base,
            ['food_id' => 54, 'nutri_id' => 5] + $base,                                                                                            ['food_id' => 54, 'nutri_id' => 28] + $base,                    ['food_id' => 54, 'nutri_id' => 33] + $base,
            ['food_id' => 55, 'nutri_id' => 5] + $base,                                                    ['food_id' => 55, 'nutri_id' => 18] + $base,
            ['food_id' => 56, 'nutri_id' => 5] + $base,
            ['food_id' => 57, 'nutri_id' => 5] + $base,
            ['food_id' => 58, 'nutri_id' => 5] + $base,                    ['food_id' => 58, 'nutri_id' => 10] + $base,                                    ['food_id' => 58, 'nutri_id' => 19] + $base,                                        ['food_id' => 58, 'nutri_id' => 29] + $base,            ['food_id' => 58, 'nutri_id' => 32] + $base,
            ['food_id' => 59, 'nutri_id' => 5] + $base,
            ['food_id' => 60, 'nutri_id' => 5] + $base,            ['food_id' => 60, 'nutri_id' => 8] + $base,
            ['food_id' => 61, 'nutri_id' => 6] + $base,
            ['food_id' => 62, 'nutri_id' => 6] + $base,                                                    ['food_id' => 62, 'nutri_id' => 19] + $base,
            ['food_id' => 63, 'nutri_id' => 6] + $base,    ['food_id' => 63, 'nutri_id' => 7] + $base,
            ['food_id' => 64, 'nutri_id' => 6] + $base,
            ['food_id' => 65, 'nutri_id' => 6] + $base,        ['food_id' => 65, 'nutri_id' => 8] + $base,
            ['food_id' => 66, 'nutri_id' => 6] + $base,                                ['food_id' => 66, 'nutri_id' => 14] + $base,
            ['food_id' => 67, 'nutri_id' => 6] + $base,
            ['food_id' => 68, 'nutri_id' => 6] + $base,
            ['food_id' => 69, 'nutri_id' => 6] + $base,
            ['food_id' => 70, 'nutri_id' => 6] + $base,
            ['food_id' => 71, 'nutri_id' => 7] + $base,                            ['food_id' => 71, 'nutri_id' => 14] + $base,                                ['food_id' => 71, 'nutri_id' => 22] + $base,    ['food_id' => 71, 'nutri_id' => 23] + $base,            ['food_id' => 71, 'nutri_id' => 26] + $base,
            ['food_id' => 72, 'nutri_id' => 7] + $base,        ['food_id' => 72, 'nutri_id' => 9] + $base,                ['food_id' => 72, 'nutri_id' => 13] + $base,                        ['food_id' => 72, 'nutri_id' => 19] + $base,                            ['food_id' => 72, 'nutri_id' => 26] + $base,            ['food_id' => 72, 'nutri_id' => 29] + $base,            ['food_id' => 72, 'nutri_id' => 32] + $base,
            ['food_id' => 73, 'nutri_id' => 7] + $base,                        ['food_id' => 73, 'nutri_id' => 13] + $base,            ['food_id' => 73, 'nutri_id' => 16] + $base,    ['food_id' => 73, 'nutri_id' => 17] + $base,    ['food_id' => 73, 'nutri_id' => 18] + $base,    ['food_id' => 73, 'nutri_id' => 19] + $base,            ['food_id' => 73, 'nutri_id' => 22] + $base,
            ['food_id' => 74, 'nutri_id' => 7] + $base,    ['food_id' => 74, 'nutri_id' => 8] + $base,        ['food_id' => 74, 'nutri_id' => 10] + $base,            ['food_id' => 74, 'nutri_id' => 13] + $base,            ['food_id' => 74, 'nutri_id' => 16] + $base,        ['food_id' => 74, 'nutri_id' => 18] + $base,    ['food_id' => 74, 'nutri_id' => 19] + $base,    ['food_id' => 74, 'nutri_id' => 20] + $base,        ['food_id' => 74, 'nutri_id' => 22] + $base,                ['food_id' => 74, 'nutri_id' => 26] + $base,        ['food_id' => 74, 'nutri_id' => 28] + $base,                ['food_id' => 74, 'nutri_id' => 32] + $base,
            ['food_id' => 75, 'nutri_id' => 7] + $base,                    ['food_id' => 75, 'nutri_id' => 12] + $base,    ['food_id' => 75, 'nutri_id' => 13] + $base,            ['food_id' => 75, 'nutri_id' => 16] + $base,        ['food_id' => 75, 'nutri_id' => 18] + $base,    ['food_id' => 75, 'nutri_id' => 19] + $base,                                ['food_id' => 75, 'nutri_id' => 27] + $base,    ['food_id' => 75, 'nutri_id' => 28] + $base,
            ['food_id' => 76, 'nutri_id' => 7] + $base,
            ['food_id' => 77, 'nutri_id' => 7] + $base,                                                            ['food_id' => 77, 'nutri_id' => 22] + $base,
            ['food_id' => 78, 'nutri_id' => 7] + $base,
            ['food_id' => 79, 'nutri_id' => 8] + $base,                                                                                                    ['food_id' => 79, 'nutri_id' => 33] + $base,
            ['food_id' => 80, 'nutri_id' => 8] + $base,
            ['food_id' => 81, 'nutri_id' => 8] + $base,
            ['food_id' => 82, 'nutri_id' => 8] + $base,            ['food_id' => 82, 'nutri_id' => 11] + $base,
            ['food_id' => 83, 'nutri_id' => 8] + $base,            ['food_id' => 83, 'nutri_id' => 11] + $base,
            ['food_id' => 84, 'nutri_id' => 8] + $base,
            ['food_id' => 85, 'nutri_id' => 8] + $base,            ['food_id' => 85, 'nutri_id' => 11] + $base,                                                                                    ['food_id' => 85, 'nutri_id' => 32] + $base,
            ['food_id' => 86, 'nutri_id' => 8] + $base,            ['food_id' => 86, 'nutri_id' => 11] + $base,                                    ['food_id' => 86, 'nutri_id' => 20] + $base,
            ['food_id' => 87, 'nutri_id' => 8] + $base,
            ['food_id' => 88, 'nutri_id' => 8] + $base,        ['food_id' => 88, 'nutri_id' => 10] + $base,
            ['food_id' => 89, 'nutri_id' => 8] + $base,                                                ['food_id' => 89, 'nutri_id' => 20] + $base,
            ['food_id' => 90, 'nutri_id' => 8] + $base,
            ['food_id' => 91, 'nutri_id' => 8] + $base,
            ['food_id' => 92, 'nutri_id' => 10] + $base,    ['food_id' => 92, 'nutri_id' => 11] + $base,        ['food_id' => 92, 'nutri_id' => 13] + $base,    ['food_id' => 92, 'nutri_id' => 14] + $base,            ['food_id' => 92, 'nutri_id' => 17] + $base,                    ['food_id' => 92, 'nutri_id' => 22] + $base,        ['food_id' => 92, 'nutri_id' => 24] + $base,        ['food_id' => 92, 'nutri_id' => 26] + $base,    ['food_id' => 92, 'nutri_id' => 27] + $base,
            ['food_id' => 93, 'nutri_id' => 10] + $base,            ['food_id' => 93, 'nutri_id' => 13] + $base,                    ['food_id' => 93, 'nutri_id' => 18] + $base,    ['food_id' => 93, 'nutri_id' => 19] + $base,                    ['food_id' => 93, 'nutri_id' => 24] + $base,    ['food_id' => 93, 'nutri_id' => 25] + $base,
            ['food_id' => 94, 'nutri_id' => 10] + $base,                                            ['food_id' => 94, 'nutri_id' => 21] + $base,
            ['food_id' => 95, 'nutri_id' => 10] + $base,
            ['food_id' => 96, 'nutri_id' => 10] + $base,                            ['food_id' => 96, 'nutri_id' => 17] + $base,                                                                ['food_id' => 96, 'nutri_id' => 33] + $base,
            ['food_id' => 97, 'nutri_id' => 11] + $base,                                    ['food_id' => 97, 'nutri_id' => 20] + $base,
            ['food_id' => 98, 'nutri_id' => 11] + $base,
            ['food_id' => 99, 'nutri_id' => 11] + $base,
            ['food_id' => 100, 'nutri_id' => 11] + $base,            ['food_id' => 100, 'nutri_id' => 14] + $base,            ['food_id' => 100, 'nutri_id' => 17] + $base,            ['food_id' => 100, 'nutri_id' => 20] + $base,
            ['food_id' => 101, 'nutri_id' => 12] + $base,                                            ['food_id' => 101, 'nutri_id' => 23] + $base,                                        ['food_id' => 101, 'nutri_id' => 33] + $base,
            ['food_id' => 102, 'nutri_id' => 14] + $base,
            ['food_id' => 103, 'nutri_id' => 14] + $base,        ['food_id' => 103, 'nutri_id' => 16] + $base,
            ['food_id' => 104, 'nutri_id' => 14] + $base,
            ['food_id' => 105, 'nutri_id' => 14] + $base,                        ['food_id' => 105, 'nutri_id' => 20] + $base,                        ['food_id' => 105, 'nutri_id' => 26] + $base,            ['food_id' => 105, 'nutri_id' => 29] + $base,
            ['food_id' => 106, 'nutri_id' => 15] + $base,                                            ['food_id' => 106, 'nutri_id' => 26] + $base,
            ['food_id' => 107, 'nutri_id' => 15] + $base,
            ['food_id' => 108, 'nutri_id' => 15] + $base,
            ['food_id' => 109, 'nutri_id' => 17] + $base,
            ['food_id' => 110, 'nutri_id' => 18] + $base,
            ['food_id' => 111, 'nutri_id' => 19] + $base,        ['food_id' => 111, 'nutri_id' => 21] + $base,    ['food_id' => 111, 'nutri_id' => 22] + $base,    ['food_id' => 111, 'nutri_id' => 23] + $base,            ['food_id' => 111, 'nutri_id' => 26] + $base,            ['food_id' => 111, 'nutri_id' => 29] + $base,
            ['food_id' => 112, 'nutri_id' => 19] + $base,                ['food_id' => 112, 'nutri_id' => 23] + $base,
            ['food_id' => 113, 'nutri_id' => 20] + $base,                        ['food_id' => 113, 'nutri_id' => 26] + $base,                        ['food_id' => 113, 'nutri_id' => 32] + $base,
            ['food_id' => 114, 'nutri_id' => 20] + $base,
            ['food_id' => 115, 'nutri_id' => 20] + $base,
            ['food_id' => 116, 'nutri_id' => 21] + $base,                                            ['food_id' => 116, 'nutri_id' => 32] + $base,
            ['food_id' => 117, 'nutri_id' => 21] + $base,                                    ['food_id' => 117, 'nutri_id' => 30] + $base,
            ['food_id' => 118, 'nutri_id' => 21] + $base,
            ['food_id' => 119, 'nutri_id' => 21] + $base,
            ['food_id' => 120, 'nutri_id' => 21] + $base,                                                ['food_id' => 120, 'nutri_id' => 33] + $base,
            ['food_id' => 121, 'nutri_id' => 21] + $base,
            ['food_id' => 122, 'nutri_id' => 21] + $base,
            ['food_id' => 123, 'nutri_id' => 21] + $base,
            ['food_id' => 124, 'nutri_id' => 28] + $base,

        ]);
    }
}
