<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;

class FoodTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $base = [
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ];

        \DB::table('food')->insert([
            ['name' => '豚肉', 'category' => 'meat', 'favorite' => '0', ] + $base,
            ['name' => '卵', 'category' => 'etc', 'favorite' => '0', ] + $base,
            ['name' => '牛乳', 'category' => 'etc', 'favorite' => '0', ] + $base,
            ['name' => '大豆', 'category' => 'vegetable', 'favorite' => '0', ] + $base,
            ['name' => 'さけ', 'category' => 'seafood', 'favorite' => '100', ] + $base,
            ['name' => '鰹節', 'category' => 'seafood', 'favorite' => '0', ] + $base,
            ['name' => 'いわし', 'category' => 'seafood', 'favorite' => '100', ] + $base,
            ['name' => 'さば', 'category' => 'seafood', 'favorite' => '100', ] + $base,
            ['name' => 'たら', 'category' => 'seafood', 'favorite' => '100', ] + $base,
            ['name' => '小麦', 'category' => 'grain', 'favorite' => '100', ] + $base,
            ['name' => 'いか', 'category' => 'seafood', 'favorite' => '100', ] + $base,
            ['name' => 'たこ', 'category' => 'seafood', 'favorite' => '100', ] + $base,
            ['name' => '貝柱', 'category' => 'seafood', 'favorite' => '100', ] + $base,
            ['name' => '干しエビ', 'category' => 'seafood', 'favorite' => '100', ] + $base,
            ['name' => '牛肉', 'category' => 'meat', 'favorite' => '100', ] + $base,
            ['name' => '湯葉', 'category' => 'etc', 'favorite' => '100', ] + $base,
            ['name' => 'あじ', 'category' => 'seafood', 'favorite' => '100', ] + $base,
            ['name' => 'オリーブ油', 'category' => 'etc', 'favorite' => '100', ] + $base,
            ['name' => 'マーガリン', 'category' => 'etc', 'favorite' => '100', ] + $base,
            ['name' => 'バター', 'category' => 'etc', 'favorite' => '100', ] + $base,
            ['name' => 'マカダミアナッツ', 'category' => 'etc', 'favorite' => '100', ] + $base,
            ['name' => '牛肉', 'category' => 'meat', 'favorite' => '100', ] + $base,
            ['name' => 'くるみ', 'category' => 'etc', 'favorite' => '100', ] + $base,
            ['name' => 'ココナツパウダー', 'category' => 'etc', 'favorite' => '100', ] + $base,
            ['name' => 'ごま', 'category' => 'etc', 'favorite' => '100', ] + $base,
            ['name' => 'アーモンド', 'category' => 'etc', 'favorite' => '100', ] + $base,
            ['name' => 'ピスタチオ', 'category' => 'etc', 'favorite' => '100', ] + $base,
            ['name' => 'ピーナッツ', 'category' => 'etc', 'favorite' => '100', ] + $base,
            ['name' => '鶏肉', 'category' => 'meat', 'favorite' => '0', ] + $base,
            ['name' => '牛脂', 'category' => 'etc', 'favorite' => '100', ] + $base,
            ['name' => 'ラード', 'category' => 'etc', 'favorite' => '100', ] + $base,
            ['name' => 'チョコレート', 'category' => 'etc', 'favorite' => '100', ] + $base,
            ['name' => 'チーズ', 'category' => 'etc', 'favorite' => '100', ] + $base,
            ['name' => 'ホイップクリーム', 'category' => 'etc', 'favorite' => '100', ] + $base,
            ['name' => 'ツナ缶', 'category' => 'seafood', 'favorite' => '0', ] + $base,
            ['name' => 'ポテトチップス', 'category' => 'etc', 'favorite' => '100', ] + $base,
            ['name' => 'ラー油', 'category' => 'etc', 'favorite' => '100', ] + $base,
            ['name' => 'マヨネーズ', 'category' => 'etc', 'favorite' => '100', ] + $base,
            ['name' => '昆布', 'category' => 'seafood', 'favorite' => '100', ] + $base,
            ['name' => 'わかめ', 'category' => 'seafood', 'favorite' => '0', ] + $base,
            ['name' => 'うなぎ', 'category' => 'seafood', 'favorite' => '100', ] + $base,
            ['name' => 'さわら', 'category' => 'seafood', 'favorite' => '100', ] + $base,
            ['name' => 'さんま', 'category' => 'seafood', 'favorite' => '100', ] + $base,
            ['name' => '練乳', 'category' => 'etc', 'favorite' => '100', ] + $base,
            ['name' => 'アイスクリーム', 'category' => 'etc', 'favorite' => '100', ] + $base,
            ['name' => 'ウィンナー', 'category' => 'meat', 'favorite' => '0', ] + $base,
            ['name' => 'からし', 'category' => 'etc', 'favorite' => '100', ] + $base,
            ['name' => 'まぐろ', 'category' => 'seafood', 'favorite' => '100', ] + $base,
            ['name' => 'のり', 'category' => 'seafood', 'favorite' => '100', ] + $base,
            ['name' => 'こしょう', 'category' => 'etc', 'favorite' => '100', ] + $base,
            ['name' => 'ひじき', 'category' => 'seafood', 'favorite' => '100', ] + $base,
            ['name' => 'たい', 'category' => 'seafood', 'favorite' => '100', ] + $base,
            ['name' => 'ぶり', 'category' => 'seafood', 'favorite' => '100', ] + $base,
            ['name' => 'そらまめ', 'category' => 'vegetable', 'favorite' => '100', ] + $base,
            ['name' => 'しめじ', 'category' => 'vegetable', 'favorite' => '100', ] + $base,
            ['name' => '油揚げ', 'category' => 'etc', 'favorite' => '0', ] + $base,
            ['name' => 'おから', 'category' => 'etc', 'favorite' => '100', ] + $base,
            ['name' => 'きな粉', 'category' => 'etc', 'favorite' => '100', ] + $base,
            ['name' => 'はまち', 'category' => 'seafood', 'favorite' => '100', ] + $base,
            ['name' => 'あなご', 'category' => 'seafood', 'favorite' => '100', ] + $base,
            ['name' => 'さとう', 'category' => 'etc', 'favorite' => '100', ] + $base,
            ['name' => '黒砂糖', 'category' => 'etc', 'favorite' => '100', ] + $base,
            ['name' => '寒天', 'category' => 'seafood', 'favorite' => '100', ] + $base,
            ['name' => '米', 'category' => 'grain', 'favorite' => '0', ] + $base,
            ['name' => 'とうもろこし', 'category' => 'vegetable', 'favorite' => '100', ] + $base,
            ['name' => 'じゃがいも', 'category' => 'vegetable', 'favorite' => '100', ] + $base,
            ['name' => 'はちみつ', 'category' => 'etc', 'favorite' => '100', ] + $base,
            ['name' => 'ココア', 'category' => 'etc', 'favorite' => '100', ] + $base,
            ['name' => 'でんぶ', 'category' => 'etc', 'favorite' => '100', ] + $base,
            ['name' => 'せんべい・あられ', 'category' => 'etc', 'favorite' => '100', ] + $base,
            ['name' => 'こんにゃく', 'category' => 'etc', 'favorite' => '100', ] + $base,
            ['name' => 'きくらげ', 'category' => 'vegetable', 'favorite' => '100', ] + $base,
            ['name' => 'しいたけ', 'category' => 'vegetable', 'favorite' => '100', ] + $base,
            ['name' => 'とうがらし', 'category' => 'vegetable', 'favorite' => '100', ] + $base,
            ['name' => 'まいたけ', 'category' => 'vegetable', 'favorite' => '100', ] + $base,
            ['name' => 'あんこ', 'category' => 'etc', 'favorite' => '100', ] + $base,
            ['name' => 'だいこん', 'category' => 'vegetable', 'favorite' => '0', ] + $base,
            ['name' => 'ごぼう', 'category' => 'vegetable', 'favorite' => '100', ] + $base,
            ['name' => 'いんげん', 'category' => 'vegetable', 'favorite' => '100', ] + $base,
            ['name' => 'にんじん', 'category' => 'vegetable', 'favorite' => '0', ] + $base,
            ['name' => 'パプリカ', 'category' => 'vegetable', 'favorite' => '100', ] + $base,
            ['name' => '春菊', 'category' => 'vegetable', 'favorite' => '100', ] + $base,
            ['name' => '大葉', 'category' => 'vegetable', 'favorite' => '100', ] + $base,
            ['name' => 'パセリ', 'category' => 'vegetable', 'favorite' => '100', ] + $base,
            ['name' => 'ほうれん草', 'category' => 'vegetable', 'favorite' => '100', ] + $base,
            ['name' => 'モロヘイヤ', 'category' => 'vegetable', 'favorite' => '100', ] + $base,
            ['name' => 'よもぎ', 'category' => 'vegetable', 'favorite' => '100', ] + $base,
            ['name' => 'かぼちゃ', 'category' => 'vegetable', 'favorite' => '100', ] + $base,
            ['name' => 'ピーマン', 'category' => 'vegetable', 'favorite' => '0', ] + $base,
            ['name' => 'いよかん', 'category' => 'fruit', 'favorite' => '100', ] + $base,
            ['name' => '桃', 'category' => 'etc', 'favorite' => '100', ] + $base,
            ['name' => '抹茶', 'category' => 'etc', 'favorite' => '100', ] + $base,
            ['name' => 'そば', 'category' => 'grain', 'favorite' => '0', ] + $base,
            ['name' => '味噌', 'category' => 'etc', 'favorite' => '100', ] + $base,
            ['name' => 'マヨネーズ', 'category' => 'etc', 'favorite' => '100', ] + $base,
            ['name' => '枝豆', 'category' => 'vegetable', 'favorite' => '100', ] + $base,
            ['name' => 'かぶ', 'category' => 'vegetable', 'favorite' => '100', ] + $base,
            ['name' => 'にら', 'category' => 'vegetable', 'favorite' => '100', ] + $base,
            ['name' => '小松菜', 'category' => 'vegetable', 'favorite' => '0', ] + $base,
            ['name' => 'ブロッコリー', 'category' => 'vegetable', 'favorite' => '100', ] + $base,
            ['name' => 'えんどう豆', 'category' => 'vegetable', 'favorite' => '100', ] + $base,
            ['name' => 'にんにく', 'category' => 'vegetable', 'favorite' => '0', ] + $base,
            ['name' => 'かつお', 'category' => 'seafood', 'favorite' => '100', ] + $base,
            ['name' => 'バナナ', 'category' => 'fruit', 'favorite' => '100', ] + $base,
            ['name' => 'しょうが', 'category' => 'etc', 'favorite' => '100', ] + $base,
            ['name' => 'あさり', 'category' => 'seafood', 'favorite' => '100', ] + $base,
            ['name' => 'しじみ', 'category' => 'seafood', 'favorite' => '100', ] + $base,
            ['name' => 'はまぐり', 'category' => 'seafood', 'favorite' => '100', ] + $base,
            ['name' => 'そら豆', 'category' => 'vegetable', 'favorite' => '100', ] + $base,
            ['name' => '納豆', 'category' => 'etc', 'favorite' => '100', ] + $base,
            ['name' => 'カレー粉', 'category' => 'etc', 'favorite' => '100', ] + $base,
            ['name' => 'さんしょう', 'category' => 'etc', 'favorite' => '100', ] + $base,
            ['name' => 'わさび', 'category' => 'etc', 'favorite' => '100', ] + $base,
            ['name' => 'レモン', 'category' => 'fruit', 'favorite' => '100', ] + $base,
            ['name' => 'キウイフルーツ', 'category' => 'fruit', 'favorite' => '100', ] + $base,
            ['name' => '梅干し', 'category' => 'etc', 'favorite' => '100', ] + $base,
            ['name' => '昆布茶', 'category' => 'etc', 'favorite' => '100', ] + $base,
            ['name' => 'ウスターソース', 'category' => 'etc', 'favorite' => '100', ] + $base,
            ['name' => '豆板醤', 'category' => 'etc', 'favorite' => '100', ] + $base,
            ['name' => 'しょうゆ', 'category' => 'etc', 'favorite' => '100', ] + $base,
            ['name' => '塩', 'category' => 'etc', 'favorite' => '100', ] + $base,
            ['name' => 'めんつゆ', 'category' => 'etc', 'favorite' => '100', ] + $base,
            ['name' => 'オイスターソース', 'category' => 'etc', 'favorite' => '100', ] + $base,
            ['name' => 'えび', 'category' => 'seafood', 'favorite' => '100', ] + $base,
        ]);
    }
}
